include/sampleflow/consumers/spurious_autocovariance.h
From a user perspective, it is very difficult to tell where this information
was produced, and so is not very useful. It's also obscures legitimate
output in projects that use SampleFlow if they want to generate screen
output themselves. As a consequence, just do what the function
documentation says: Return a default-constructed object.
=> Do not produce output to the screen.

tests/covariance_matrix_01.cc, tests/spurious_autocovariance_01.cc
These comments explain what *doesn't* work, but that is not useful information
to the reader: The reader wants to understand what *does* happen in a given
file. It's also information that tends to go out of date pretty quickly: If
we implement the ability to work with things other than valarray, we would
have to update comments in files that are unrelated to what we are
implementing.
@MantautasRimkus -- FYI.
=> Remove some commentary.

tests/covariance_matrix_01.cc
There is no need to explicitly #include a BOOST header file that is already
included in the covariance_matrix.h file that uses this class.
@MantautasRimkus -- FYI
=> Remove unnecessary include file.

include/sampleflow/element_access.h
This also necessitates moving the 'size()' function before the 'get_nth_element()' function.
@MantautasRimkus FYI.
=> Assert that accessing an element is valid.

tests/covariance_matrix_03.cc, tests/covariance_matrix_03.output
Like #20, but adds a test that computes the covariance matrix for a scalar sample type -- i.e., a 1x1 matrix.
@MantautasRimkus: So this works now, but there is the same issue with the normalization.
=> Add a test for computing the covariance matrix of scalars.

include/sampleflow/consumers/spurious_autocovariance.h
The beta here is really just a collection of sums of vectors. It could be represented by a matrix, but it is easier to just store a collection of vectors since we never need to do any linear algebra.
@MantautasRimkus
=> Use a better type for beta in the SpuriousAutocovariance.

include/sampleflow/consumers/spurious_autocovariance.h
In the SpuriousAutocovariance consumer, whenever we access an element of the sample,
use the Utilities::get_nth_element() function. Similarly when querying the size of
a sample, use Utilities::size().
The idea is that this will eventually allow us to also use this class for
scalar sample types.
=> Some prep-work.

tests/CMakeLists.txt
This makes sure that all tests compile without any warnings, and by extension
that none of the code that is included from SampleFlow header files into these
tests produces any warnings.
=> Treat all warnings in tests as errors.

mcmc_test.cc
This file has outlived its usefulness -- it used to illustrate how to use SampleFlow, but we now have all of the tests to show this.
That said, it should at least compile. Make sure it can be, following the changes in #74.
=> Make mcmc_test.cc compile again after the changes to the MH sampler.

tests/CMakeLists.txt
@dawsoneliasen This will require you to install the `numdiff` program. It should be available as a package on your system via `apt-get`.
=> Use numdiff to execute tests.

tests/maximum_probability_sample_01.cc, tests/maximum_probability_sample_02.cc
Adjust the tests introduced in #79 to the syntax needed for #74, following the fix for #63.
=> Adjust the calling syntax for the MH sampler.

tests/CMakeLists.txt
Specifically, the presence of a .result file is not sufficient to indicate
that a test succeeds: If a test fails the first time around, but
generates a .result file, then it will succeed the second time around
regardless of whether the 'diff' is good or not...
=> Fix the logic of running a test.

include/sampleflow/consumers/covariance_matrix.h, include/sampleflow/types.h
std::conj() *always* returns a std::complex number, but that is not useful if the argument is in fact not complex-valued at all, and consequently breaks the classes that use std::conj on non-complex objects.
This is a follow-up to #97 . @dawsoneliasen -- you could probably have caught this if you had run `ctest` to run *all* tests, not just the new ones: You'd have found that all existing tests for the `CovarianceMatrix` consumer failed. That's of course not what we want :-)
=> Introduce Utilities::conj() that actually works.

.github/workflows/SampleFlow-test.yml
@dawsoneliasen -- that was actually quite simple. github has a wizard that helps set up a .yml file for CI actions. I followed it and it automatically committed the CI file into my master branch. I accidentally had a typo in there (I believe), so this is a follow-up PR that fixes that and, with some luck, also tests whether this actually works...
=> Fix a typo in the YML CI file.

tests/CMakeLists.txt
The reference output files were not found when I created a separate build directory. Fix this.
=> allow running tests out of source

CMakeLists.txt
I could not configure as my boost is not installed in /usr/include/. Fix this:
- set boost include dirs found from FIND_PACKAGE
- make boost required
- make header check work by setting CMAKE_REQUIRED_INCLUDES
=> fix boost detection

.github/workflows/SampleFlow-test.yml
- the CI runners have only two cores, so using -j8 is not helpful
- let ctest output details when a test fails.
=> CI: small ctest fix

CMakeLists.txt, tests/CMakeLists.txt
This allows propagating dependencies from SampleFlow to programs that use this library.
=> Describe SampleFlow as an interface library.

CMakeLists.txt
Specifically, the std_cxx_11 target property was only added to cmake in 3.7.
=> Request appropriate cmake version.

include/sampleflow/producers/differential_evaluation_mh.h
Follow-up to #138. In particular, try to avoid `i` for anything other than just counting indices.
=> Rename a variable.

include/sampleflow/producers/differential_evaluation_mh.h
Another follow-up to #138. This doesn't actually change anything, I'm just making sure we use the type for indexing into the chains that `std::vector` internally uses to index its elements.
=> Use the correct integer type when indexing into the number of chains.

include/sampleflow/producers/differential_evaluation_mh.h, tests/differential_evaluation_mh_producer_01.output
Closes #142, Closes #144 . Use the correct index for creating mating partners, skip crossover in generation 0. This did move the sample mean much further away from the true mean, however the sample mean seems to converge to the theoretical mean as sample size increases.
=> fix demh producer and update output

include/sampleflow/consumers/stream_output.h
`std::endl` doesn't just put an endline into the stream, but also calls the `flush()` function on the stream. The latter in turn causes the current contents of the memory buffer to be sent to disk, which is causing a lot of file system traffic if done often. This can be avoided by only putting an endline `\n` into the buffer, but leaving the flush operation to whenever that buffer is full.
=> Use '\n' instead of 'std::endl'.

include/sampleflow/auxiliary_data.h, include/sampleflow/concepts.h, include/sampleflow/config.h, include/sampleflow/connections.h, include/sampleflow/consumer.h, include/sampleflow/element_access.h, include/sampleflow/filter.h, include/sampleflow/parallel_mode.h, include/sampleflow/producer.h, include/sampleflow/scope_exit.h, include/sampleflow/types.h
Then also include it from all important files.
=> Introduce config.h.

tests/differential_evaluation_mh_producer_01.cc
=> Fix a test.
