- include/sampleflow/consumers/acceptance_ratio.h
@MantautasRimkus -- here are my updates to the acceptance ratio code.
Didn't you write tests for these new classes? I've learned to believe that I make mistakes every time I write something that I can't test -- but I also don't want to write a test if you already have one :-)
> Update the code that computes the acceptance ratio.

- tests/count_samples_01.cc
- tests/covariance_matrix_01.cc
- tests/discard_first_n_01.cc
- tests/metropolis_hasting_producer_01.cc
- tests/metropolis_hasting_producer_02.cc
- tests/spurious_autocovariance_01.cc
@MantautasRimkus -- FYI. I should probably show you sometime how I do the indentation (and talk about *why* I do this.)
> Apply our usual indentation style.

- tests/acceptance_ratio_01.cc
- tests/average_cosinus_01.cc
This is a follow-up to #9, just indenting everything with the script.
@MantautasRimkus -- FYI.
> Indent the tests introduced in #9.

- include/sampleflow/consumers/covariance_matrix.h
@MantautasRimkus -- it's an obvious bug I introduced. It's not clear to me how I managed to commit this, running the tests should have shown that it doesn't work.
> Fix a bug introduced in #21.

- include/sampleflow/consumers/covariance_matrix.h
In particular, no longer state the (attempt at a) derivation of the update formula used.
Also, make sure we have the 1/(N-1) factor right.
@MantautasRimkus -- FYI.
> Update the documentation of the CovarianceMatrix class.

- include/sampleflow/consumers/spurious_autocovariance.h
In particular, make sure that `value_type` is used in the same way as in other classes: As the type that is returned by `get()`. The rest is really just a little bit of restructuring. I have ideas how to this better, but that has to wait for another day.
> Small edits to the autocovariance computation.

- tests/metropolis_hasting_producer_01.cc
- tests/metropolis_hasting_producer_02.cc
> Update comments in a few places.

- include/sampleflow/producers/metropolis_hastings.h
- tests/metropolis_hasting_producer_03.cc
- tests/metropolis_hasting_producer_03.output
@MantautasRimkus -- this was what we discussed on Friday.
> Make the MH sampler also send aux data about whether the sample was accepted

- include/sampleflow/consumers/average_cosinus.h
- include/sampleflow/consumers/spurious_autocovariance.h
Just small stuff -- in particular, make it so that latex can understand all of the formulas.
@MantautasRimkus -- FYI.
> Update documentation in a number of places.

- include/sampleflow/consumers/spurious_autocovariance.h
@MantautasRimkus -- this uses a more appropriate data structure for storing past samples, namely a `std::deque`: https://en.cppreference.com/w/cpp/container/deque .
> Use a std::deque to store past samples.

- include/sampleflow/consumers/spurious_autocovariance.h
@MantautasRimkus -- here are a few more updates to the auto-covariance.
> Update more things about the auto-covariance.

- tests/spurious_autocovariance_01.cc
> Simplify a test.

- include/sampleflow/consumers/covariance_matrix.h
> Use a pre-defined type.

- include/sampleflow/consumers/spurious_autocovariance.h
Following a suggestion by @MantautasRimkus .
> Use a better way to determine the scalar type.

- CMakeLists.txt
> Closes #64 Remove signals from required components

- tests/README.md
> Better document how to add a test.

- tests/conversion_01.cc
- tests/conversion_02.cc
This updates the changes in #70 and #69 and uses the same indentation style used everywhere else.
@dawsoneliasen Ask me about this on Wednesday.
> Apply the auto-indentation script.

- include/sampleflow/producers/metropolis_hastings.h
- tests/acceptance_ratio_01.cc
- tests/acceptance_ratio_02.cc
- tests/acceptance_ratio_03.cc
- tests/average_cosinus_01.cc
- tests/conversion_01.cc
- tests/conversion_02.cc
- tests/covariance_matrix_01.cc
- tests/metropolis_hasting_producer_01.cc
- tests/metropolis_hasting_producer_02.cc
- tests/metropolis_hasting_producer_03.cc
- tests/spurious_autocovariance_01.cc
- tests/spurious_autocovariance_05.cc
> Fix the bug in the Metropolis-Hastings sampler.

- tests/covariance_matrix_04.cc
- tests/covariance_matrix_05.cc
- tests/covariance_matrix_06.cc
- tests/metropolis_hasting_producer_10.cc
Run `make indent` to normalize white space.
> Adjust white space.

- include/sampleflow/producers/differential_evaluation_mh.h
- tests/differential_evaluation_mh_producer_02.cc
- tests/differential_evaluation_mh_producer_02.output
> Off by one

- include/sampleflow/producers/differential_evaluation_mh.h
@dawsoneliasen As discussed today.
> Get rid of an explicit template argument.

- include/sampleflow/producers/delayed_rejection_mh.h
> Reference a delayed rejection publication.

- include/sampleflow/producers/delayed_rejection_mh.h
- tests/delayed_rejection_mh_producer_01.cc
Addresses the one last comment in #136.
> Pass an argument by reference.

- include/sampleflow/producers/metropolis_hastings.h
- tests/metropolis_hasting_producer_14.cc
- tests/metropolis_hasting_producer_14.output
- tests/metropolis_hasting_producer_15.cc
- tests/metropolis_hasting_producer_15.output
- tests/metropolis_hasting_producer_16.cc
- tests/metropolis_hasting_producer_16.output
- tests/metropolis_hasting_producer_17.cc
- tests/metropolis_hasting_producer_17.output
> Handle the case of zero probabilities more graceful.

- doc/references.bib
- include/sampleflow/producers/metropolis_hastings.h
> Write documentation for the AM method.

- include/sampleflow/producers/delayed_rejection_mh.h
@dawsoneliasen -- FYI. I'm not super happy right now with having to extract the samples out of the vector of samples+likelihood, but it's still better than having to evaluate the log likelihood.
This seems to pass the tests on my local system.
> Make sure that the DR algorithm doesn't have to repeatedly evaluate the log likelihood

- include/sampleflow/producer.h
Oops. Gets us some way towards resolving #228.
> Make destructor virtual.

- include/sampleflow/consumer.h
We can get away with not sharing the state by appropriate use of move construction.
> Use std::future, not std::shared_future.
